version: '3'

name: "prd-mon-wp"
services:
  prd_mysqld-exporter:
    image: prom/mysqld-exporter:v0.14.0     # Forced to this version, with newer version doesn't work and can't connect with mariadb
    container_name: "prd_mysqld-exporter"
    restart: unless-stopped
    user: root
    # Uncomment next line if you want access, port not required be published
    # ports:
    #   - "9104:9104"
    environment:
      # Uncomment other parameters to be added
      - "DATA_SOURCE_NAME=${MYSQL_MON_USER}:${MYSQL_MON_PASSWORD}@(${PRD_WORDPRESS_WEBSITE_URL_WITHOUT_HTTP}:3306)/"
      - "collect.auto_increment.columns=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
      # - "collect.global_status=true"
      # - "collect.global_variables=true"
      # - "collect.slave_status=true"
      # - "collect.binlog_size=true"
      # - "collect.info_schema.innodb_metrics=true"
      # - "collect.engine_tokudb_status=true"
      # - "collect.info_schema.innodb_tablespaces=true"
      # - "collect.info_schema.tables=true"
      # - "collect.info_schema.tables.databases=true"
      # - "collect.info_schema.processlist=true"
      # - "collect.info_schema.processlist.min_time=true"
      # - "collect.perf_schema.eventsstatements=true"
      # - "collect.perf_schema.eventsstatements.limit=true"
      # - "collect.perf_schema.eventsstatements.timelimit=true"
      # - "collect.perf_schema.eventsstatements.digest_text_limit=true"
      # - "collect.perf_schema.indexiowaits=true"
      # - "collect.perf_schema.file_events=true"
      # - "collect.perf_schema.eventswaits=true"
    # depends_on:
    # - prometheus
    networks:
      - mon-net

  prd_nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: "prd_nginx-exporter"
    restart: unless-stopped
    # Uncomment ports lines if you want access, port not required be published
    # ports:
    # - 9113:9113
    command:
    - '-nginx.scrape-uri'
    - 'http://${PRD_WORDPRESS_WEBSITE_URL_WITHOUT_HTTP}:${PRD_NGINX_PORT}/status'      # Change value with host:port required
    # - '-web.listen-address'
    # - '9113'
    # depends_on:
    # - prometheus
    networks:
      - mon-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    ports: ["9200:9200"]
    labels:
      co.elastic.logs/enabled: false
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "TAKE_FILE_OWNERSHIP=1"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
    networks:
      - mon-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports: ["5601:5601"]
    labels:
      co.elastic.logs/enabled: false
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    depends_on: ["elasticsearch"]
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
    networks:
      - mon-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: filebeat
    command: --strict.perms=false -e
    user: root
    restart: on-failure
    labels:
      co.elastic.logs/enabled: false
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    volumes:
      - ./filebeat/:/usr/share/filebeat/:ro
      - filebeat:/usr/share/filebeat/data
      - ${PRD_DB_LOGS_PATH}:/var/log/mysql
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: ["elasticsearch", "kibana"]
    networks:
      - mon-net

networks:
  mon-net:
    name: mon-net

volumes:
  db_logs: {}
  elasticsearch: {}
  filebeat: {}