{
 "title": "WordPress",
 "tags": [
  "WordPress",
  "FrontEnd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "PRDNGINX Request/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"prd_nginx-exporter:9113\"}[$__rate_interval])",
     "legendFormat": "PRDNGINX Request/s"
    }
   ]
  },
  {
   "title": "STGNGINX Request/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"stg_nginx-exporter:9113\"}[$__rate_interval])",
     "legendFormat": "STG NGINX Request/min"
    }
   ]
  },
  {
   "title": "PRD WordPress Post Published",
   "type": "gauge",
   "description": "WordPress Statistics",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wp_posts_total{status=\"published\", instance=\"wp.local:80\"}",
     "legendFormat": "WordPress Post Published"
    }
   ]
  },
  {
   "title": "PRDNGINX Conections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"prd_nginx-exporter:9113\"}",
     "legendFormat": "PRD NGINX Active Connections"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"prd_mysqld-exporter:9113\"}",
     "legendFormat": "PRD NGINX Waiting Connections"
    }
   ]
  },
  {
   "title": "STG WordPress Post Published",
   "type": "gauge",
   "description": "WordPress Statistics",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wp_posts_total{status=\"published\", instance=\"stgwp.local:4080\"}",
     "legendFormat": "WordPress Post Published"
    }
   ]
  },
  {
   "title": "STGNGINX Conections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"stg_nginx-exporter:9113\"}",
     "legendFormat": "STG NGINX Active Connections"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"stg_mysqld-exporter:9113\"}",
     "legendFormat": "STG NGINX Waiting Connections"
    }
   ]
  }
 ]
}